### ISSUE TITLE
Subtract with Overflow

### ISSUE THREAD

**Issue by slimjim2234** [icicle-emu/icicle-emu#59]
### Problem
`icicle-emu/sleigh/sleigh-runtime/src/lib.rs:479:30:
attempt to subtract with overflow`

`varnode_offset = parent_reg.size - varnode_offset - size;`

Code:
```
/// Maps a SLEIGH register to an internal VarNode ID and offset.
    pub fn map_sleigh_reg(&self, offset: u32, size: u8) -> Option<(pcode::VarId, u8)> {
        let &(id, mut varnode_offset) = self.register_mapping.get(&offset)?;
        let parent_reg = &self.registers[id as usize];
        if self.big_endian {
            varnode_offset = parent_reg.size - varnode_offset - size;
        }
        Some((id, varnode_offset))
    }
```

Variables:
`{name:(5497, 5500), size:4, offset:2060, ...}`
`offset: 2063`
`size: 4`
`varnode_offset: 3`
`id: 105`
`parent_reg.size: 4`

The parent reg is `sr3`

### Trace
`rust_panic (@rust_panic:4)
std::panicking::rust_panic_with_hook (@std::panicking::rust_panic_with_hook:147)
std::panicking::begin_panic_handler::{{closure}} (@std::panicking::begin_panic_handler::{{closure}}:32)
std::sys_common::backtrace::__rust_end_short_backtrace (@std::sys_common::backtrace::__rust_end_short_backtrace:5)
rust_begin_unwind (@rust_begin_unwind:18)
core::panicking::panic_fmt (@core::panicking::panic_fmt:13)
core::panicking::panic (@core::panicking::panic:16)
sleigh_runtime::SleighData::map_sleigh_reg (<omitted>/icicle-emu/sleigh/sleigh-runtime/src/lib.rs:479)
icicle_cpu::cpu::Cpu::var_for_offset (<omitted>/icicle-emu/icicle-cpu/src/cpu.rs:351)
<icicle_cpu::cpu::UncheckedExecutor as icicle_cpu::exec::interpreter::PcodeExecutor>::load_mem (<omitted>/icicle-emu/icicle-cpu/src/cpu.rs:585)
icicle_cpu::exec::interpreter::load (<omitted>/icicle-emu/icicle-cpu/src/exec/interpreter.rs:629)
icicle_cpu::exec::interpreter::interpret (<omitted>/icicle-emu/icicle-cpu/src/exec/interpreter.rs:500)
icicle_cpu::cpu::Cpu::interpret_unchecked (<omitted>/icicle-emu/icicle-cpu/src/cpu.rs:454)
icicle_jit::runtime::run_interpreter (<omitted>/icicle-emu/icicle-jit/src/runtime.rs:145)
555556D3808D (@555556d3808d..555556d3810d:3)
icicle_vm::Vm::run_block_jit (<omitted>/icicle-emu/icicle-vm/src/lib.rs:497)
icicle_vm::Vm::run (<omitted>/icicle-emu/icicle-vm/src/lib.rs:198)
`

**Comment by mchesser** [comment]
This is caused by a register offset that crosses a register boundary. 

e.g., The SLEIGH specification defines the registers something like:

```
0x800: +0  +1  +2  +3  +4  +5  +6  +7  ...
       [ sr0         ] [ sr1         ] ...
```

When we execute: `[7c 60 25 26] "mfsrin r3,r4"` with `r4 = 0x20000000` we get: `r3 = register[0x800 + 2]` it results in the following access:

```
0x800: +0  +1  +2  +3  +4  +5  +6  +7  ...
       [ sr0         ] [ sr1         ] ...
               [0x800 + 2    ]
```

Which causes issues in Icicle because the execution model isolates all the accesses.


I think this is actually a partially a SLEIGH bug, since indexing into a partial register offset seems incorrect to me (since the PowerPC manual defines `mfsrin rD,rB` to be: `rD <- SLB(rB[32-35])`). The line here:

https://github.com/icicle-emu/ghidra/blob/50230050fa58bd40d5a96cab9c167fc55bc92a76/Ghidra/Processors/PowerPC/data/languages/ppc_instructions.sinc#L3039

Should probably be changed to:

```
	D = *[register]:4 ($(SEG_REGISTER_BASE)+(tmp*4));
```

(And in a couple of other places that do the same thing).


That said Icicle should avoid crashing in this scenario. While I could add support for reads that cross multiple register boundaries, I'm tempted to just make return an emulator exception in these cases instead.

**Comment by slimjim2234** [comment]
I appreciate the diagnosis.  This is as much a learning experience about SLEIGH as it is about the emulator itself.
I agree, I don't know of a scenario where crossing a register boundary would be ok.  Throwing an exception makes sense.
I made the change to the slaspec to test and it worked out.
Much appreciated!
